config/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = [
    path("", include("resume.urls")),
    path("admin/", admin.site.urls),
]

resume/urls.py
from django.urls import path

from . import views


app_name = "resume"
urlpatterns = [
    path("", views.index, name="index"),
]

resume/models/about.py
from django.core.validators import MinLengthValidator
from django.db import models


class About(models.Model):

    first_name = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    last_name = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    place = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    contact = models.EmailField()
    country = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    description = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

resume/models/portfolio.py
from django.core.validators import MinLengthValidator
from django.db import models
import django.utils


class PortfolioCategory(models.Model):
    name = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    description = models.TextField()

    def __str__(self):
        return f"{self.name}"


class Portfolio(models.Model):
    title = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    subtitle = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    description = models.TextField()
    link = models.URLField()

    publishing_date = models.DateField(default=django.utils.timezone.now)

    portfolio_categories = models.ManyToManyField(PortfolioCategory)

    class Meta:
        ordering = ["-publishing_date"]

    def __str__(self):
        return f"{self.title}"

resume/models/project.py
from django.core.validators import MinLengthValidator
from django.db import models


class ProjectManager(models.Manager):
    def progression(self):
        projects = self.get_queryset().filter()

        if not projects:
            return 0

        achieved_projects = projects.filter(achieved=True)
        progression = len(achieved_projects) * 100 / len(projects)

        return progression


class Project(models.Model):

    name = models.CharField(max_length=100, validators=[MinLengthValidator(5)])

    number = models.IntegerField()

    achieved = models.BooleanField(default=False)
    pending = models.BooleanField(default=False)

    objects = ProjectManager()

    class Meta:
        ordering = ["number"]

    def __str__(self):
        return f"{self.name}"

resume/models/social.py
from django.core.validators import MinLengthValidator
from django.core.validators import URLValidator
from django.db import models


class Social(models.Model):

    url = models.URLField(validators=[URLValidator])
    title = models.CharField(max_length=100, validators=[MinLengthValidator(2)])
    icon = models.CharField(max_length=50, validators=[MinLengthValidator(5)])

    def __str__(self):
        return f"{self.title}"

resume/views.py
from django.shortcuts import render

from resume.models import about
from resume.models import portfolio
from resume.models import project
from resume.models import social


def index(request):
    resume = about.About.objects.all().first()

    socials = social.Social.objects.all()

    projects = project.Project.objects.all()
    progression = project.Project.objects.progression()

    portfolio_elements = portfolio.Portfolio.objects.all()

    context = {
        "resume": resume,
        "socials": socials,
        "projects": {"projects": projects, "progression": progression},
        "portfolio": portfolio_elements,
    }

    return render(request, "resume/index.html", context=context)

resume/templates/resume/index.html
{% extends "base.html" %}
{% block title %}CV - Guillaume Ojardias{% endblock title %}
{% block content %}
{% include "resume/index/_about.html" %}
{% include "resume/index/_portfolio.html" %}
{% include "resume/index/_progress.html" %}
{% include "resume/index/_credits.html" %}
{% endblock content %}

resume/templates/resume/index/_about.html
<!-- About-->
<section class="resume-section" id="about">
	<div class="resume-section-content">
		<h1 class="mb-0">{{ resume.first_name }} <span class="text-primary">{{ resume.last_name }}</span></h1>
		<div class="subheading mb-5">
			{{ resume.place }} · {{ resume.country }} · <a href="mailto:{{ resume.contact }} ">{{ resume.contact }}</a>
		</div>
		<p class="lead mb-5 text-justify">
			{{ resume.description|safe|linebreaks }}
		</p>
		{% if socials %}
		<div class="social-icons">
			{% for link in socials %}
			<a class="social-icon" href="{{ link.url }}" title="{{ link.title }}" target="_blank" rel="noreferrer">
				<i class="{{ link.icon }}"></i>
			</a>
			{% endfor %}
		</div>
		{% endif %}
	</div>
</section>
<hr class="m-0" />

resume/templates/resume/index/_credits.html
<!-- Credits -->
<section class="resume-section" id="credits">
	<div class="resume-section-content">
		<h2 class="mb-0">Credits</h2>
		<h3 class="subheading mb-5">Tools used for this website</h3>
		<ul>
			<li>Back-end:
				<ul>
					<li>
						Coded with <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer">Django</a>
					</li>
					<li>
						Code formatting <a href="https://github.com/psf/black" target="_blank" rel="noreferrer">Black</a>
					</li>
					<li>
						PEP8's rules
						<a href="https://github.com/rocioar/flake8-django" target="_blank" rel="noreferrer">Flake8 for Django</a>
					</li>
				</ul>
			</li>
			<li>Front-end:
				<ul>
					<li>
						Template "Resume" from
						<a href="https://startbootstrap.com/" target="_blank" rel="noreferrer">Start Bootstrap</a>
					</li>
				</ul>
			</li>
			<li>Tools:
				<ul>
					<li>The best IDE in the world: <a href="https://www.vim.org" target="_blank" rel="noreferrer">Vim</a></li>
				</ul>
			</li>
			<li>Host:
				<ul>
					<li>Hosted by <a href="https://www.digitalocean.com" target="_blank" rel="noreferrer">Digital Ocean</a></li>
				</ul>
			</li>
		</ul>
	</div>
</section>

resume/templates/resume/index/_portfolio.html
<!-- Portfolio -->
<section class="resume-section" id="portfolio">
	<div class="resume-section-content">
		<h2 class="mb-5">Portfolio</h2>
		{% if portfolio %}
		<div class="row row-cols-1 row-cols-md-3">
			{% for item in portfolio %}
			<div class="col mb-4">
				<div class="card">
					<div class="card-header">
						<h3>{{ item.title }}</h3>
					</div>
					<div class="card-body">
						<h4 class="card-title">{{ item.subtitle }}</h4>
						<p class="card-text">{{ item.description|safe|linebreaks }}</p>
						<a href="{{ item.link }}" class="btn btn-primary" target="_blank" rel="noreferrer">
							More details
						</a>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
		<h3>No elements to show yet</h3>
		{% endif %}
</section>
<hr class="m-0" />

resume/templates/resume/index/_progress.html
<!-- Training progression -->
<section class="resume-section" id="progress">
	<div class="resume-section-content">
		<h2 class="mb-1">Training progress</h2>
		{% if projects %}
		<div class="progress mb-3">
			{% with progression=projects.progression|floatformat:"0" %}
			<div id="projects-progression" class="progress-bar progress-bar-striped progress-bar-animated bg-primary"
				role="progressbar" aria-valuenow="{{ progression }}" aria-valuemin="0" aria-valuemax="100">
				{{ progression }}%
			</div>
			{% endwith %}
		</div>
		<script>
			const progressBar = document.getElementById('projects-progression');
			const progression = "width: " + progressBar.innerText + ";";
			progressBar.setAttribute("style", progression);
		</script>
		<h3 class="subheading my-0">Projects for the training:</h3>
		<div class="row justify-content-center">
			<ul class="list-group projects">
				{% for project in projects.projects %}
				<li class="list-group-item">
					{% with properties="mr-2 nf nf-fa-" %}
					{% if project.achieved %}
					<i class="{{ properties }}check_circle_o"></i>
					{% elif project.pending %}
					<i class="{{ properties }}play_circle_o"></i>
					{% else %}
					<i class="{{ properties }}circle_o"></i>
					{% endif %}
					{% endwith %}
					<span>{{ project.name }}</span>
				</li>
				{% endfor %}
			</ul>
		</div>
		{% else %}
		<h3 class="subheading my-0">No current training</h3>
		{% endif %}
	</div>
</section>
<hr class="m-0" />

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
	<meta name="description" content="Resume for Guillaume Ojardias" />
	<meta name="author" content="Guillaume Ojardias" />
	<title>{% block title %}{% endblock title %}</title>
	<link rel="apple-touch-icon" sizes="57x57" href="{% static "dist/assets/favicons/apple-icon-57x57.png" %}">
	<link rel="apple-touch-icon" sizes="60x60" href="{% static "dist/assets/favicons/apple-icon-60x60.png" %}">
	<link rel="apple-touch-icon" sizes="72x72" href="{% static "dist/assets/favicons/apple-icon-72x72.png" %}">
	<link rel="apple-touch-icon" sizes="76x76" href="{% static "dist/assets/favicons/apple-icon-76x76.png" %}">
	<link rel="apple-touch-icon" sizes="114x114" href="{% static "dist/assets/favicons/apple-icon-114x114.png" %}">
	<link rel="apple-touch-icon" sizes="120x120" href="{% static "dist/assets/favicons/apple-icon-120x120.png" %}">
	<link rel="apple-touch-icon" sizes="144x144" href="{% static "dist/assets/favicons/apple-icon-144x144.png" %}">
	<link rel="apple-touch-icon" sizes="152x152" href="{% static "dist/assets/favicons/apple-icon-152x152.png" %}">
	<link rel="apple-touch-icon" sizes="180x180" href="{% static "dist/assets/favicons/apple-icon-180x180.png" %}">
	<link rel="icon" type="image/png" sizes="192x192" href="{% static "dist/assets/favicons/android-icon-192x192.png" %}">
	<link rel="icon" type="image/png" sizes="32x32" href="{% static "dist/assets/favicons/favicon-32x32.png" %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static "dist/assets/favicons/favicon-96x96.png" %}">
	<link rel="icon" type="image/png" sizes="16x16" href="{% static "dist/assets/favicons/favicon-16x16.png" %}">
	<link rel="manifest" href="{% static "dist/assets/favicons/manifest.json" %}">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="{% static "dist/assets/favicons/ms-icon-144x144.png" %}">
	<meta name="theme-color" content="#ffffff">
	<!-- Font Awesome icons (free version)-->
	<script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
	<!-- Google fonts-->
	<link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
	<link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
	<!-- Core theme CSS (includes Bootstrap)-->
	<link href="{% static "dist/css/styles.css" %}" rel="stylesheet" />
</head>

<body id="page-top">
	<!-- Navigation-->
	<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
		<a class="navbar-brand js-scroll-trigger" href="#page-top">
			<span class="d-block d-lg-none">Guillaume Ojardias</span>
			<span class="d-none d-lg-block"> <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static "dist/assets/img/profile.jpg" %}"
					alt="Guillaume's profile picture" />
			</span>
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			{% block nav_links %}
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger" href="{% url "resume:index" %}#about">
						About
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger" href="{% url "resume:index" %}#portfolio">
						Portfolio
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger" href="{% url "resume:index" %}#progress">
						Training progress
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link js-scroll-trigger" href="{% url "resume:index" %}#credits">
						Credits
					</a>
				</li>
			</ul>
			{% endblock nav_links %}
		</div>
	</nav>
	<!-- Page Content-->
	<div class="container-fluid p-0">
		{% block content %}{% endblock content %}
	</div>
	<!-- Bootstrap core JS-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
	<!-- Third party plugin JS-->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
	<!-- Core theme JS-->
	<script src="{% static "dist/js/scripts.js" %}"></script>
</body>

</html>